project_id = "jtojmvquqdkvibsraydq"

[functions.parse-data-file]
verify_jwt = false

[functions.clean-data-with-ai]
verify_jwt = true

[functions.suggest-field-mappings]
verify_jwt = false

[functions.scoped-ai-assistant]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false
